services:
  rpi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/rpi
    stdin_open: true  # Keep STDIN open for interactive shell
    tty: true         # Allocate a pseudo-TTY for terminal
    entrypoint: /bin/bash
